more cli tests

diff --git a/.github/workflows/test-refgenie-cli.yml b/.github/workflows/test-refgenie-cli.yml
--- a/.github/workflows/test-refgenie-cli.yml
+++ b/.github/workflows/test-refgenie-cli.yml
@@ -51,6 +51,18 @@ jobs:
       run: |
         refgenie build -c genomes/g.yaml t7/fasta_child --recipe tests/data/recipe_child.json
         ./tests/assert_in_file.sh genomes/g.yaml fasta_child 0
+        if [ -L `refgenie seek -c genomes/g.yaml t7/fasta_child` ]; then
+            echo "`refgenie seek -c genomes/g.yaml t7/fasta_child` exists."
+        else
+            echo "Error: `refgenie seek -c genomes/g.yaml t7/fasta_child` does not exist."
+            exit 1
+        fi
+        if [ -d genomes/data/162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b/fasta_child/default ]; then
+            echo "'genomes/data/162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b/fasta_child/default' exists."
+        else
+            echo "Error: 'genomes/data/162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b/fasta_child/default' does not exist."
+            exit 1
+        fi
 
     - name: refgenie list
       working-directory: ./genomes
@@ -65,11 +77,38 @@ jobs:
     - name: refgenie build fasta
       run: refgenie build -c genomes/g.yaml t7/fasta --files fasta=tests/data/t7.fa.gz --recipe tests/data/recipe_parent.json
 
-    - name: refgenie change alias
+    - name: refgenie set aliases
       run: |
-        refgenie alias remove -c genomes/g.yaml --digest t7
-        refgenie alias set -c genomes/g.yaml --aliases t7_new --digest 162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b
+        refgenie alias set -c genomes/g.yaml --aliases t7_new t7_new1 --digest 162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b
         ./tests/assert_in_file.sh genomes/g.yaml t7_new 0
+        ./tests/assert_in_file.sh genomes/g.yaml t7_new1 0
+        if [ -L `refgenie seek -c genomes/g.yaml t7_new/fasta_child` ]; then
+            echo "`refgenie seek -c genomes/g.yaml t7_new/fasta_child` exists."
+        else
+            echo "Error: `refgenie seek -c genomes/g.yaml t7_new/fasta_child` does not exist."
+            exit 1
+        fi
+        if [ -L `refgenie seek -c genomes/g.yaml t7_new1/fasta_child` ]; then
+            echo "`refgenie seek -c genomes/g.yaml t7_new1/fasta_child` exists."
+        else
+            echo "Error: `refgenie seek -c genomes/g.yaml t7_new1/fasta_child` does not exist."
+            exit 1
+        fi
+
+    - name: refgenie remove aliases
+      run: |
+        refgenie alias set -c genomes/g.yaml --aliases t7_another --digest 162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b
+        refgenie alias remove -c genomes/g.yaml --aliases t7_new t7_new1 t7 --digest 162a8922a1529a5ec1ce0e69e65d7476936258586a79ba0b
+        ./tests/assert_in_file.sh genomes/g.yaml t7_new 1
+        ./tests/assert_in_file.sh genomes/g.yaml t7_new1 1
+        ./tests/assert_in_file.sh genomes/g.yaml t7 1
+        ./tests/assert_in_file.sh genomes/g.yaml t7_another 0
+        if [ -L `refgenie seek -c genomes/g.yaml t7_new/fasta_child` ]; then
+            echo "`refgenie seek -c genomes/g.yaml t7_new/fasta_child` exists."
+          exit 1
+        else
+            echo "Error: `refgenie seek -c genomes/g.yaml t7_new/fasta_child` does not exist."
+        fi
 
     - name: refgenie get aliases
       run: |
